### ISSUE TITLE
Extremely low framerate

### ISSUE THREAD

**Issue by eric29** [keijiro/BodyPixBarracuda#2] opened 2021-08-21 21:17 UTC
Running the project as is, or with my own image or video, runs at about 5 frames/sec and video lags at about 0.5 f/s.

Using unity 2021.1.11f1

**Comment by eric29** [comment] 2021-08-21 21:36
I forgot to mention that I changed the resolution to 1920 x 1080 in the Image Source output (which should be the normal resolution for most videos. Unless this was not intended to be used with hd resolution?

**Comment by keijiro** [comment] 2021-08-22 05:14
> I forgot to mention that I changed the resolution to 1920 x 1080 in the Image Source output (which should be the normal resolution for most videos. Unless this was not intended to be used with hd resolution?

This doesn't affect the speed of inference. It may affect the accuracy, though.

**Comment by keijiro** [comment] 2021-08-22 05:15
- What is the specs of your computer?
- Does it reproduce with the default settings?

**Comment by eric29** [comment] 2021-08-23 23:24
> This doesn't affect the speed of inference. It may affect the accuracy, though.

Sorry, I meant the resolution in the visualizer component.

I have a lenovo laptop with an i9 16gb ram and gtx1650. Shouldn't be the problem I believe. 

I did have to modify slightly the image source script as for some reason, every time I chose video texture and chose my video, it would always just revert to URL with Test2.mp4 as the file. So I just created my own video player component and directed the script to use that instead of creating the component in the script.

I can try to add my asset folder with the demo video I was testing with, but not sure how to do this? My video has a large crowd in the back, which I thought was the problem at first, but I blacked out the crowd to test and it's still extremely laggy with no difference.

**Comment by keijiro** [comment] 2021-08-24 00:06
> Sorry, I meant the resolution in the visualizer component.

Then, the cause of the problem is obvious. The resolution is too high. BodyPix is not a HD-ready lightweight model. You should run it in a low resolution. I think 320x240 or 480x360 is a better choice for GTX 1650.

**Comment by keijiro** [comment] 2021-08-24 00:06
I'm closing this issue now. Please feel free to reopen it for further problems.

**Closed by keijiro** 2021-08-24 00:06 UTC
Labels: question
